---
- name: Install Brew packages
  homebrew:
    name: "{{ item }}"
    state: present
  with_items:
    - meld
    - git
    - wget
    - caskroom/cask

- name: Install via cask
  command: "brew cask install {{ item }}" 
  with_items:
    - postman
    - visual-studio-code
    - slack
    - keepassxc
    - firefox
    - google-chrome
    - google-hangouts
    - virtualbox
    - virtualbox-extension-pack
    - vagrant
    - docker
    - hipchat
    - iterm2
