---
- homebrew_tap:
    name: caskroom/cask

- name: Install Brew packages
  homebrew:
    name: "{{ item }}"
    state: present
  with_items:
    - meld
    - git
    - wget
    - brew-cask

- name: Install via brew cask
  homebrew_cask: 
    name: "{{ item }}"
    state: present 
  with_items:
    - postman
    - visual-studio-code
    - slack
    - keepassxc
    - firefox
    - google-chrome
    - google-hangouts
    - virtualbox
    - virtualbox-extension-pack
    - vagrant
    - docker
    - hipchat
    - iterm2
