---
- file:
    path: ~/.bashrc
    state: touch

- name: Get NVM
  get_url:
    url: "https://raw.githubusercontent.com/creationix/nvm/{{ nvm_version }}/install.sh"
    dest: /tmp/nvm.sh

- name: Install NVM
  shell: bash /tmp/nvm.sh

- name: Install Latest LTS of NodeJS
  shell: . ~/.bashrc && nvm install --lts

- name: Update npm
  shell: . ~/.bashrc && npm -g update npm

